-- SQL Keywords
-- 1. Add - 	Adds a column in an existing table
-- 2. Returns true if all of the subquery values meet the condition
-- 3.ALTER 	Adds, deletes, or modifies columns in a table, or changes the data type of a column in a table
-- 4.  And 	Only includes rows where both conditions is true
-- 5. Any Returns true if any of the subquery values meet the condition // basically OR
-- 6 As 	Renames a column or table with an alias
-- asc 	Sorts the result set in ascending order
-- BETWEEN Selects values within a given range
-- CASE	Creates different outputs based on conditions